# Introduction to NumPy and Pandas

Both these libraries are two critical Python libraries that help structure data in arrays & DataFrame and contains a lot of built-in functions for the data analysis. <br>
Pandas is Python's most widely used library for data analysis and contains functions for accessing, aggregating, joining and analyzing data. Its data structur, DataFrame is analogous to SQL tables/ Excel Worksheet.<br>
NumPy is an open source library that is the universal standard for working with the numerical data in Python and forms the foundation of the other libraries like - Pandas and Scikit-learn. Pandas DataFrames are built on the NumPy array and can leverage NumPy functions.    

In [ ]:
# Importing the NumPy Library

import numpy as np

## NumPy Arrays

NumPy arrays are fixed-size containers of items that are more efficient than Python lists or tuple for data processing
1. They only store a single data types. 
2. They can be one dimensional or multi-dimensional
3. Array elements can be modified but the size of the array can't change. 

When a NumPy array is created, they are stored in the contiguos memmory location
<br>
NumPy arrays are a ndarray Python datatype, which stands for n-dimensional arrays.  

### Array Properties 

NumPy arrays have the following key properties:



> 1. **ndim** - the number of dimensions/axes in the array
2. **shape** - the size of the array for each dimension
3. **size** - the total number of elements in the array
4. **dtype** - datatype of the elements in the array. 




### Creating a NumPy arrays

<b>array() function</b> can be used to convert Python list and tuples into the NumPy array. You can pass the datatypes along with the number of dimension required. <br>
```
np.array(list, dtype = , ndim = )
```
1. The function can up-cast the datatypes based on the list/tuple passed in the 
functions. <br>
2. we can create a multi dimensional array with a nested list, where each nested list is a dimension. For this case the nested list should be of same length.  

In [ ]:
# Let's create a python list/tuple and we will begin creating an array from the list

mydata = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

#creating an array

array = np.array(mydata)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# Accessing the properties of the array we have just created

print("ndim:{}".format(array.ndim))
print("shape:{}".format(array.shape))
print("size:{}".format(array.size))
print("dtype:{}".format(array.dtype))

ndim:1
shape:(12,)
size:12
dtype:int64


In [ ]:
# Creating a nested list for a 2D array
mydata = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

#creating an array

array = np.array(mydata)
array


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# Accessing the properties of the array we have just created

print("ndim:{}".format(array.ndim))
print("shape:{}".format(array.shape))
print("size:{}".format(array.size))
print("dtype:{}".format(array.dtype))

ndim:2
shape:(4, 3)
size:12
dtype:int64


In [ ]:
# Numpy creates an object of type nd.array 
type(array)

numpy.ndarray

<b><font color  = "#735d78">ones</font></b> - creates an array of ones of given size, as a float by default. <br>
``` np.ones((rows, cols), dtype)```


In [ ]:
one_array = np.ones((2,2))
one_array

array([[1., 1.],
       [1., 1.]])

<b><font color  = "#735d78">zeros</font></b> - creates an array of zeros of given size, as a float by default. <br>
``` np.zeros((rows, cols), dtype)```

In [ ]:
zero_array = np.zeros((2,2))
zero_array

array([[0., 0.],
       [0., 0.]])

<b><font color  = "#735d78">arange</b></font> - creates an array of integers with given start and stop values and a step size. Only stop is mandatory argument and is not inclusive. 
``` np.arange(start, stop, step)```

In [ ]:
array = np.arange(1, 10, 0.5)
array

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

<b><font color  = "#735d78">linspace</b></font> - creates an array of floats with given start and stop values with n elements, separated by consistent step size. Stop is inclusive. 
``` np.linspace(start, stop, n)```

In [ ]:
array = np.linspace(0, 10, 20)
array

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

<b><font color  = "#735d78">full</b></font> - creates an array filled with X of the required shape. <br>
``` np.full(shape, X, dtype)```
<br><br>
<b><font color  = "#735d78">full_like</b></font> - Returns an array with the same shape and type as passed and the values filled are X <br>
``` np.full_like(array, X)```

### Random number generation 

Numpy comes with a randomization module called numpy.random for sampling or generating a random sample of data.You can create a reliably random array each time you run by setting a seed using np.random.seed(number). 

You can create random number arrays from variety of distributions using NumPy functions and methods (Great for sampling and simulation)

default_rng - Creates a random number generator (the seed is for reproducibility)
``` np.default_rng(seed)```

random - Works on the default random number genetor, returns n random numbers from uniform distribution between 0 & 1
``` rng.random(n)```

normal - Works on the default random number generator, returns n random numbers from the normal distribution with a given mean and standard deviation. 
``` rng.normal(mean, stdev, n)```

### Indexing & slicing Arrays

Indexing and slicing works the same way as in the base Python. The indexing starts at ZERO. Array also has the ability to use the Negative index to start indexing from the end (Just as the base python list)<br>
<br>
When you do slicing, the data is not copied, it just returns a view of the original data.Therefore when you make a change in the sliced version, the original array is also changed. The Reason NumPy does this is due to memory optimization. To create the actual copy of the sliced array use <font color = "red"> copy()</font> function. 


<b><font color  = "#735d78">Indexing Style </b></font><br>
For a single Dimension Array:<br>
For Indexing```array[index]``` is used to get an element at the required position. This would return a single value
<br> 
For Slicing ```array[Start:Stop:Step]``` is used to return a subset of the element.  
<br>  

For a 2D Array:<br> 
For Indexing```array[row index, column index]``` is used and it returns a single element at the coordinate 
<br>
For slicing in both the Dimensions(row & column) use the Slicing notation on both the dimensions ```array[row_start:stop:step, col_start:stop, step]```
<br>
1. Proving only ":" would return all the rows/columns
2. The start index is inclusive, while the stop index is exclusive
3. You can also index an array with a list (the list of the index you want). With way you can access an element repeatedly by repeating the index.   

In [ ]:
#Let's create an Array, and apply the slice and dice concept to get an element

array = np.arange(25).reshape(5,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Let's Get the forst element from the array - 
array[0,0]

0

In [ ]:
# First row of the array
array[0, :]

array([0, 1, 2, 3, 4])

In [ ]:
 # Getting the Last two columns from the array
 array[:,3:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [ ]:
# Let's say we want all the element on the diagonal. we will reshape the array into 1D and then extract the element

array.reshape(25,1)[[0,6,12,18,24]]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24]])

### Methods on Array

reshape - changes an array into the specified dimesion, if compatible. 
``` array.reshape(rows, cols)```<br>
Also note that the order of the elements remains the same after reshaping 

**Transponse** ``` array.T``` helps in transposing the dataset, where the rows are converted into columns and vice verse. 

### Array Operations

Arithmetic operators can be used to perform array operation. 

<br>
We can multiply the two array if they are of the same length. Element wise operation happens. 


The array operations are applied via vectorization and broadcasting, which eliminates the need to loop through the array's elements. 

### Filtering an Array

You can <b>filter arrays</b> by indexing them with logical test. Only the array elements in positions where the logical test returns <b>TRUE</b> are returned as the final output. <br>
When we performs a logical test on an array,it will perform the logical test on every element of the array and will return TRUE for all the element where the condition was met and FALSE where the condition was not met. <br>
Hence, performing logical test on a NumPy array results in a <b>Boolean array</b> with the results of the logical test on the elements of the array. We then use this boolean array to filter our array.<br>
Indexing an array with a Boolean array results an array with the elements where the Boolean value is TRUE. <br>
You can filter the arrays based on multiple logical test. Use <b> "|"</b> for or condition and <b>"&"</b> for and conditions
<br>
<br>
<b> Always store the complex filtering criterias in a variable </b>

<br>
You can fitler the values in one array, based on the values in another array. Use the Boolean array returned from another array to index the array you want to filter. Length of both the array sshould be same. <br>

### Modifying the Array Values

Use the index of the position where you want to update the value.
<br>
You can also use the filter concept to change a set of values which meet the certain criteria. 

### Where 

<b>Where()</b> is a NumPy function which performs logical test and returns a given value if the test is true or another value if the test is False. 
<br>
```
np.where(logical test, value if TRUE, Value if FALSE)
```
You can pass the nested where functions to test multiple conditions. 

### Array Functions

This refers to reducing any array to 1 dimension using array.flatten()


The numPy functions are applied to each element of the array. For example np.sqrt(array) returns a new array where each element is squared

### Missing Data in the array

NumPy allows you to have missing data in your array and still maintain the datatype of the elements by using np.nan to represent these elements. Numeric arrays(integers or floats) with nan elements automatically assume the float datatype.